
# Project information
site_name: 'KICKLE'
site_description: 'KICKLE Admin Configuration docs'
site_author: 'Kickle'
site_url: 'https://docs.kickle.com'
docs_dir: Docs

# Copyright
copyright: 'Copyright &copy; 2018 Kickle'

# Documentation and theme
theme: 'material'

# Options
extra:
  logo: ''
  palette:
    primary: 'deep purple'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'icone.png'
# Extensions 
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Page tree
pages:
  - Home: index.md
  - Kickle Admin Guide:
    - 1 - Requirements: admin-guide/requirements and compatibility.md
    - 2 - Network:
      - 2.1 - Protocols and port requirements : admin-guide/protocols and port requirements.md
      - 2.2 - Bandwith : admin-guide/bandwidth.md
      - 2.3 - Proxy : admin-guide/proxy.md    
    - 3 - Configuration :      
      - 3.1 - Configuration On-Premise: admin-guide/Configuring Exchange On-Premise and Skype for Business On-Premise Accounts.md
      - 3.2 - Configuration On Line : admin-guide/Configuring Exchange Online and Skype for Business Online (Office 365) Accounts.md
      - 3.3 - Configuration Hybrid : admin-guide/Configuring Exchange Online and Skype for Business On Premise (Hybrid).md
      - 3.4 - Features Configuration : admin-guide/features-configuration.md  
      - 3.5 - Connecting and Setting Up Kickle : admin-guide/Connecting and setting Kickle.md 
    - 4 - Security: admin-guide/customize security settings.md
    - 5 - Update: admin-guide/how to update.md
    - 6 - Assistance: admin-guide/help menu and remote assistance.md
  - Manage:
    - Start in Admin mode : manage/admin-mode.md
    - Join Kickle to Active Directory : manage/ad.md
    - Manage Kickle with Microsoft Intune : manage/intune.md
  - Additional Features:
    - Wifi Hotspot : features/hotspot.md
    - Additional Applications : features/application.md
  - Beta Features :
    - Voila : beta/voila.md
    - Standalone Install : beta/installer.md
  

 
  
